### ISSUE TITLE
<a href> tag getting added to Gdoc URL when paste into shortcode (in Gutenberg)

### ISSUE THREAD

**Issue by tomharbo** [cuny-academic-commons/google-docs-shortcode#15]
When adding the shortcode in the block editor, I first pasted the templated shortcode ("[gdoc link="THE LINK YOU COPIED" height="800"]" and then pasted in the copied Gdoc link. The problem I encountered is that the editor auto-coverts the link to a link with the <a href> tags. Unless I go into the HTML view and take away the <href> tags, the embed doesn't work.

**Comment by r-a-y** [comment]
Hi @tomharbo, sorry, just saw this issue!

The instructions in the readme.md file need to be amended for the new Block Editor.

I've been working on an update that will add a new Google Docs block, but for now, you'll need to add the **Shortcode** block to the editor and then you can paste the `[gdoc]` shortcode into that block and the Google Doc should embed properly once you publish your document

See the attached GIF:

![Shortcode Block GIF](https://user-images.githubusercontent.com/505921/60015886-18535d00-9674-11e9-8d14-39b88418532d.gif)

I'll leave this issue open because I need to amend the instructions.

**Comment by tomharbo** [comment]
Thanks, Ray! I realized this after reporting the issue. Please keep me
posted when you update the instructions and I'll pass those on to faculty
who I work with at BMCC.

Best,
Tom

**Comment by r-a-y** [comment]
@tomharbo - Sorry for the delay on this, totally slipped my mind!

I've created an entry on the wiki for using the Shortcode block here:
https://github.com/cuny-academic-commons/google-docs-shortcode/wiki/Using-the-Shortcode-block-with-the-Block-Editor

**Comment by tomharbo** [comment]
Thanks!
